name: Run traffic_speeds.py every 3 minutes

on:
  schedule:
    - cron: '*/3 * * * *'  # every 3 minutes
  workflow_dispatch:       # allows manual trigger as well

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or any version you need

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run script
        run: python traffic_speeds.py
